name: deploy

on:
  push:
    branches: [ main ]

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install openssh-client bash rsync
      - name: Set up SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          eval $(ssh-agent -s)
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_HOST_KEY1 }}" > ~/.ssh/known_hosts
          echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
          rsync -av --delete --exclude='.env' . root@164.92.181.109:/var/www/Bingo
          ssh root@164.92.181.109 -t << 'EOF'
            cd /var/www/Bingo
            pm2 restart lottery 
          EOF